### ISSUE TITLE
Build error - Syntax error: 0.05081em*rem/px isn't a valid CSS value.

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-sdk#141]
```
/*
Syntax error: 0.05081em*rem/px isn't a valid CSS value.
        on line 99 of /Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/frameworks/compass/stylesheets/compass/typography/_vertical_rhythm.scss, in `adjust-font-size-to'
        from line 160 of /www/ckeditor-sdk/template/theme/sass/partials/_global.scss
        from line 8 of /www/ckeditor-sdk/template/theme/sass/sdk.scss

Backtrace:
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/frameworks/compass/stylesheets/compass/typography/_vertical_rhythm.scss:99:in `adjust-font-size-to'
/www/ckeditor-sdk/template/theme/sass/partials/_global.scss:160
/www/ckeditor-sdk/template/theme/sass/sdk.scss:8
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/script/number.rb:266:in `to_s'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:299:in `visit_prop'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (3 levels) in visit_mixin'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `map'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (2 levels) in visit_mixin'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block in visit_mixin'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:70:in `perform_arguments'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:263:in `visit_mixin'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:320:in `visit_rule'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:320:in `visit_rule'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:227:in `block in visit_import'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:227:in `map'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:227:in `visit_import'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:7:in `visit'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/tree/root_node.rb:20:in `render'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/engine.rb:315:in `_render'
/Users/p/.rvm/gems/ruby-2.1.3@global/gems/sass-3.2.19/lib/sass/engine.rb:262:in `render'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/compiler.rb:139:in `block (2 levels) in compile'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/compiler.rb:126:in `timed'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/compiler.rb:138:in `block in compile'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/logger.rb:45:in `red'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/compiler.rb:137:in `compile'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/compiler.rb:118:in `compile_if_required'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/compiler.rb:103:in `block (2 levels) in run'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/compiler.rb:101:in `each'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/compiler.rb:101:in `block in run'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/compiler.rb:126:in `timed'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/compiler.rb:100:in `run'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/commands/update_project.rb:45:in `perform'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/commands/base.rb:18:in `execute'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/commands/project_base.rb:19:in `execute'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/lib/compass/exec/sub_command_ui.rb:15:in `run!'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/bin/compass:30:in `block in <top (required)>'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/bin/compass:44:in `call'
/Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/bin/compass:44:in `<top (required)>'
/Users/p/.rvm/gems/ruby-2.1.3/bin/compass:23:in `load'
/Users/p/.rvm/gems/ruby-2.1.3/bin/compass:23:in `<main>'
/Users/p/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/p/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
*/
body:before {
  white-space: pre;
  font-family: monospace;
  content: "Syntax error: 0.05081em*rem/px isn't a valid CSS value.\A         on line 99 of /Users/p/.rvm/gems/ruby-2.1.3/gems/compass-0.12.7/frameworks/compass/stylesheets/compass/typography/_vertical_rhythm.scss, in `adjust-font-size-to'\A         from line 160 of /www/ckeditor-sdk/template/theme/sass/partials/_global.scss\A         from line 8 of /www/ckeditor-sdk/template/theme/sass/sdk.scss"; }
```

**Comment by Reinmar** [comment]
Fixed after running:

```gem update --system```
