### ISSUE TITLE
Issues with building SDK on Windows

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor-sdk#167]
After the recent changes, I am unable to build the SDK on my local Windows machine.

Environment:
* Windows 8.1
* git version 2.5.1.windows.1
* Node v0.12.7
* ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]
* Compass 1.0.3 (Polaris)

I cloned the CKEditor SDK repository from scratch, went through all the steps listed in the [README](https://github.com/ckeditor/ckeditor-sdk/blob/master/README.md) file. I am unable to build the entire package - while the samples can be generated, the docs cannot. Build log:

```
at@at-cks-dell MINGW64 /c/dev/ckeditor-sdk (master)
$ grunt build
Running "compass:sdk-build-css" (compass) task

Running "shell:sdk-build" (shell) task
Building offline version of CKEditor SDK.
Removing old release directory C:\dev\ckeditor-sdk\build\offline
Building CKEditor from presets...
CKEditor Presets Builder

========================

Checking/Updating CKBuilder...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0




Copying extra plugins...



Deleting build/4.5.4/standard-all...



Building the 'standard' preset...

Copying files (relax, this may take a while)


    Time taken.....: 107.037seconds

Merging language files

    Time taken.....: 7.538seconds

Generating plugins sprite image

Building ckeditor.js


Minifying ckeditor.js

Created ckeditor.js (498KB)

    Time taken.....: 12.285seconds
Building skins

    Time taken.....: 6.606seconds

Cleaning up target folder

    Time taken.....: 1.675seconds


Creating compressed files...


    Created ckeditor_4.5.4_(standard).zip...: 2717916 bytes (50% of original)

    Created ckeditor_4.5.4_(standard).tar.gz: 1768303 bytes (33% of original)

    Time taken.....: 3.728seconds

==========================
Release process completed:

    Number of files: 2581
    Total size.....: 5401026 bytes

    Time taken.....: 138.869seconds


Removing added plugins...

Removing plugins/scayt/
Removing plugins/wsc/



Build created into the "build" directory.


Building CKEditor finished.
CKEditor version: 4.5.4
CKEditor path: C:\dev\ckeditor-sdk/vendor/ckeditor-presets/build/4.5.4/standard-all/ckeditor/
Copying template files
Copying sample files
Copying vendor files
Copying CKEditor files
Copying Mathjax files
Reading sample directory C:\dev\ckeditor-sdk\samples
Validating links in samples and index
Parsing categories
Copying guides
Fixing guides links
Building documentation.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn grunt ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

Done, without errors.
```

My `ckeditor-dev` and `ckeditor-docs` repositories are up to date, both on master. I can build docs off the `ckeditor-docs` repo (running `grunt`) with no issues. I can go directly to `c:\dev\ckeditor-sdk\docs\`, run `grunt` there and docs are built all right in `c:\dev\ckeditor-sdk\docs\build\`.

I can see the following on StackOverflow: http://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js but honestly, I don't think I'm able to follow any of the "solutions" there.

Additionally, when I try to re-run `grunt build` again, I am getting the following error:

```
at@at-cks-dell MINGW64 /c/dev/ckeditor-sdk (master)
$ grunt build
Running "compass:sdk-build-css" (compass) task

Running "shell:sdk-build" (shell) task
A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file build already exists.
Error occurred while processing: build.

Done, without errors.
```

There are two directories in `ckeditor-sdk` that I need to remove manually to proceed: `build` and `-p`. This wasn't needed before (and empty `-p` is new).

**Comment by Reinmar** [comment]
I merged PR #169 to master.
